"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Aluguel_1 = require("./model/Aluguel");
var Cliente_1 = require("./model/Cliente");
var Carro_1 = require("./model/Carro");
var Moto_1 = require("./model/Moto");
var locacao_1 = require("./service/locacao");
var locacao = new locacao_1.Locacao();
var cliente1 = new Cliente_1.Cliente("19149480766", Cliente_1.TipoCarteira.A);
var cliente2 = new Cliente_1.Cliente("19149480766", Cliente_1.TipoCarteira.B);
//const carro1 = new Carro("ABCD1234", "Vermelho", "Honda Civic", 75.00, 4);
//const carro2 = new Carro("DCBA4321", "Preto", "Toyota Camry", 120.00, 4);
var moto1 = new Moto_1.Moto("EFGH5678", "Azul", "Honda CBR600RR", 45.00);
var moto2 = new Moto_1.Moto("HGFE8765", "Amarelo", "Harley-Davidson Sportster", 60.00);
var aluguel = new Aluguel_1.Aluguel(moto1, cliente1);
locacao.addVeiculo(new Carro_1.Carro("ABCD1234", "Vermelho", "Honda Civic", 75.00, 4));
locacao.addVeiculo(new Moto_1.Moto("ABCD1234", "Preto", "Toyota Camry", 120.00));
console.log(locacao.buscarTodosVeiculos());
